"""数据库模块"""

from .postgres_store import (
    init_db,
    get_connection,
    UserRecord,
    ClassRecord,
    HomeworkRecord,
    create_user,
    get_user_by_username,
    get_user_by_id,
    list_user_class_ids,
    create_class_record,
    get_class_by_id,
    get_class_by_invite_code,
    list_classes_by_teacher,
    list_classes_by_student,
    add_student_to_class,
    count_class_students,
    list_class_students,
    create_homework_record,
    get_homework,
    list_homeworks,
    # 工作流状态
    WorkflowState,
    save_workflow_state,
    get_workflow_state,
    update_workflow_status,
    HomeworkSubmission,
    save_homework_submission,
    get_homework_submissions,
    upsert_homework_submission_grade,
    list_student_submissions,
    update_homework_submission_status,
    upsert_assistant_concepts,
    list_assistant_concepts,
    save_assistant_mastery_snapshot,
    list_assistant_mastery_snapshots,
)

# 批改历史和学生结果使用 PostgreSQL 版本
from .postgres_grading import (
    GradingHistory,
    save_grading_history,
    get_grading_history,
    list_grading_history,
    StudentGradingResult,
    save_student_result,
    get_student_results,
    get_student_result,
    GradingPageImage,
    get_page_images,
    get_page_images_for_student,
)

# PostgreSQL 图片存储
from .postgres_images import (
    BatchImage,
    save_batch_images,
    save_batch_images_concurrent,
    get_batch_images,
    get_batch_images_as_bytes_list,
    delete_batch_images,
    get_batch_image_count,
)

__all__ = [
    "init_db",
    "get_connection",
    "UserRecord",
    "ClassRecord",
    "HomeworkRecord",
    "create_user",
    "get_user_by_username",
    "get_user_by_id",
    "list_user_class_ids",
    "create_class_record",
    "get_class_by_id",
    "get_class_by_invite_code",
    "list_classes_by_teacher",
    "list_classes_by_student",
    "add_student_to_class",
    "count_class_students",
    "list_class_students",
    "create_homework_record",
    "get_homework",
    "list_homeworks",
    "WorkflowState",
    "save_workflow_state",
    "get_workflow_state",
    "update_workflow_status",
    "GradingHistory",
    "save_grading_history",
    "get_grading_history",
    "list_grading_history",
    "StudentGradingResult",
    "save_student_result",
    "get_student_results",
    "get_student_result",
    "GradingPageImage",
    "get_page_images",
    "get_page_images_for_student",
    "HomeworkSubmission",
    "save_homework_submission",
    "get_homework_submissions",
    "upsert_homework_submission_grade",
    "list_student_submissions",
    "update_homework_submission_status",
    "upsert_assistant_concepts",
    "list_assistant_concepts",
    "save_assistant_mastery_snapshot",
    "list_assistant_mastery_snapshots",
    # PostgreSQL 图片存储
    "BatchImage",
    "save_batch_images",
    "save_batch_images_concurrent",
    "get_batch_images",
    "get_batch_images_as_bytes_list",
    "delete_batch_images",
    "get_batch_image_count",
]
